# tu by nemalo byt nic lebo ako sa zavola config server vzdy sa zobere tento subor a prepise lokalny application.yml 
#server:
#  port: 8191
#spring:
#  cloud:
#    config:
 #     server:
  #      git:
 #         uri: https://github.com/krish/spring-cloud-config
   #       search-paths:
   #        - '*service'



